### ISSUE TITLE
有相关的原理性的东西介绍么？

### ISSUE THREAD

**Issue by ainilife** [liuwenzi/GTL#1]

**Comment by liuwenzi** [comment]
你好。
这个项目主要是用来解决共用一个数据库的异构分布式系统间的事务问题的。
因为之前在异构的分布式系统（如: 前端PHP + 后端Java）中，一些情况下需要两套系统中以数据库事务的形式对数据进行操作. 而异构系统又没法在代码层面直接共享同一个数据库事务链接或者对象.
因为业务的特殊性也没法使用消息队列进行业务的解耦处理.
所以就有了这个项目.

这个项目的原理主要就是: 
   通过一个中间系统**代持数据库链接**, **代理数据库操作**, 并**提供通用接口来供其他系统进行数据库事务操作和处理**.

其他的系统功能都相对来说比较简单. 就不细说了.
如果有兴趣了解的话 可以看下代码或者问我 /呲牙 :)
